services:
    backend:
        build: .
        image: alas-backend
        container_name: my-backend
        restart: unless-stopped
        ports:
            - '3000:3000'
        env_file:
            - .env
        networks:
            - app-network
        volumes:
            - .:/app:cached
            - node_modules:/app/node_modules

volumes:
    node_modules:

networks:
    app-network:
        driver: bridge
